
CREATE TABLE branches (
    branch_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(100) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    address     TEXT        NOT NULL
);
 
CREATE TABLE customers (
    customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(50)  NOT NULL,
    date_of_birth DATE         NOT NULL,
    city          VARCHAR(100) NOT NULL
);
 
CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    branch_id   INTEGER REFERENCES branches(branch_id),
    position    VARCHAR(50)  NOT NULL CHECK (position IN ('Teller', 'Manager', 'Analyst')),
    salary      NUMERIC(10, 2) NOT NULL
);
 
CREATE TABLE accounts (
    account_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INTEGER REFERENCES customers(customer_id),
    branch_id    INTEGER REFERENCES branches(branch_id),
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('SAVINGS', 'CHECKING', 'CREDIT')),
    balance      NUMERIC(12, 2) NOT NULL,
    opened_date  DATE NOT NULL
);
 
CREATE TABLE transactions (
    transaction_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       INTEGER REFERENCES accounts(account_id),
    employee_id      INTEGER REFERENCES employees(employee_id),
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    amount           NUMERIC(10, 2) NOT NULL,
    transaction_date TIMESTAMP NOT NULL
);